add applications healthy check

diff --git a/ansible/roles_ocp_workloads/ocp4_workload_oai_parasol_insurance/tasks/workload.yaml b/ansible/roles_ocp_workloads/ocp4_workload_oai_parasol_insurance/tasks/workload.yaml
--- a/ansible/roles_ocp_workloads/ocp4_workload_oai_parasol_insurance/tasks/workload.yaml
+++ b/ansible/roles_ocp_workloads/ocp4_workload_oai_parasol_insurance/tasks/workload.yaml
@@ -84,6 +84,32 @@
   command: "oc apply -f /tmp/ocp4_workload_oai_parasol_insurance_repo/{{ ocp4_workload_oai_parasol_insurance_yaml_file_path }}"
   when: git_clone.changed
 
+- name: Wait 30s for the Applications to be created
+  pause:
+    seconds: 30
+
+- name: Wait for ArgoCD Applications to be fully healthy
+  block:
+  - name: Check if all Applications are fully healthy
+    shell: |
+      if oc get applications.argoproj.io -n openshift-gitops \
+          -o jsonpath="{.items[*].status.health.status}" | grep -qvE '^(\s*Healthy\s*)+$'; then
+        exit 1
+      else
+        exit 0
+      fi
+    register: sync_check
+    retries: 360               # Retry for 360 attempts (15s * 360 = 1.5 hour)
+    delay: 15                  # Wait 15 seconds between retries
+    until: sync_check.rc == 0  # Continue retrying until all Applications are healthy
+    failed_when: sync_check.rc != 0
+    changed_when: false
+
+  - name: Fail if Applications did not sync within the timeout
+    fail:
+      msg: "Timeout reached! Not all Applications are healthy."
+    when: sync_check.rc != 0
+
 # Leave this as the last task in the playbook.
 - name: workload tasks complete
   debug:
