update

diff --git a/ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/task-update-jt.yaml.j2 b/ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/task-update-jt.yaml.j2
--- a/ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/task-update-jt.yaml.j2
+++ b/ansible/roles_ocp_workloads/ocp4_workload_tekton_execution_environment/templates/section2/pipelines/task-update-jt.yaml.j2
@@ -39,8 +39,17 @@ spec:
           -H 'Content-Type: application/json' \
           -u '$(params.USER):$(params.PASSWORD)'
           )
+        
+        data="${FIND_JT:: -3}"
+        response_status="${FIND_JT: -3}"
+        if [ "${response_status}" -ne "200" ]; then
+            printf "%s" "${data}"
+            printf "%s" "Find JT Error: HTTP repsonse is ${response_status}"
+            exit 1
+        fi
+          
         echo "find jt ${FIND_JT: -3}"
-        JT_END_POINT=$(echo -n ${FIND_JT:: -3} |jq  -r '.results[] | select(.name == "$(params.JOB_TEMPLATE)") | .url'
+        JT_END_POINT=$(echo -n ${FIND_JT:: -3} |jq  -r '.results[] | select(.name == "$(params.JOB_TEMPLATE)") | .url')
         echo ${AC_EE_ID}
         echo ${JT_END_POINT}
         
@@ -51,3 +60,11 @@ spec:
           -d '{"execution_environment": ${AC_EE_ID} }'
         )
         echo "UPDATE jt ${UPDATE_JT: -3}"
+        data="${UPDATE_JT:: -3}"
+        response_status="${UPDATE_JT: -3}"
+        if [ "${response_status}" -ne "200" ]; then
+            printf "%s" "${data}"
+            printf "%s" "Update JT Error: HTTP repsonse is ${response_status}"
+            exit 1
+        fi
+        echo "Job Template $(params.JOB_TEMPLATE) has been updated"
